services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app2
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - smartbook-net
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - minio
      - elasticsearch

  nginx:
    image: nginx:alpine
    container_name: nginx2
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - smartbook-net
    depends_on:
      - app
      - elasticsearch

  db:
    image: postgres:17-alpine
    container_name: db2
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartbook
      POSTGRES_USER: smartbook_user
      POSTGRES_PASSWORD: StrongPassword_123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    networks:
      - smartbook-net
    command: ["postgres", "-c", "listen_addresses=*", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin2
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartbook.ru
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - smartbook-net
    depends_on:
      - db

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI (MinIO Console)
    environment:
      MINIO_ROOT_USER: smartbook
      MINIO_ROOT_PASSWORD: smartbook123
    volumes:
      - minio_data:/data
    networks:
      - smartbook-net
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: smartbook_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - smartbook-net
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  smartbook-net:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  es_data:
